- hosts: localhost
  connection: local
  become: true

  handlers:
      - name: Reload systemd
        ansible.builtin.systemd:
            daemon_reload: yes

  tasks:
      - name: Debian System Setup
        block:
            - name: Update all packages
              ansible.builtin.apt:
                  update_cache: yes
                  upgrade: dist

            - name: Install essential tools
              ansible.builtin.apt:
                  name:
                      - git
                      - curl
                      - htop
                      - npm
                      - nodejs
                      - vim
                  state: present

            - name: Copy udev rules
              ansible.builtin.copy:
                  src: ./configs/udev/
                  dest: /etc/udev/rules.d/
                  owner: root
                  group: root
                  mode: '0644'
              notify: Reload systemd

            - name: Enable and start essential services
              ansible.builtin.systemd:
                  name: '{{ item }}'
                  enabled: yes
                  state: started
              loop:
                  - ssh
              ignore_errors: yes
        when: ansible_os_family == "Debian"
